const String url = 'http://204.48.17.106:3030/';
// const String url = 'http://10.0.2.2:3030/';
const String urlImages = 'http://204.48.17.106:3030/';
const String versionService = 'api/v1/';
const String methodLogin = 'auth/login';
const String methodFindAllCourses = 'courses/findAllToSyllabus';
const String methodGetImageCourse = 'courses/getImage/';
const String methodFindAllSyllabusBlocks = 'syllabus-block/findAllToSyllabus/';
const String methodFindOneBlockPage = 'block-pages/';
